// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        int32
	Data      []byte
	CreatedAt pgtype.Timestamp
}

type Outbox struct {
	ID            int64
	AggregateType string
	AggregateID   int64
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamp
	ProcessedAt   pgtype.Timestamp
}
