// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (data)
VALUES ($1)
RETURNING id, data, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, data []byte) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, data)
	var i Order
	err := row.Scan(&i.ID, &i.Data, &i.CreatedAt)
	return i, err
}

const deleteOldOrdersBatch = `-- name: DeleteOldOrdersBatch :exec
DELETE FROM orders
WHERE id IN (
    SELECT id
    FROM orders
    WHERE created_at < now() - $1::interval
    LIMIT $2
)
`

type DeleteOldOrdersBatchParams struct {
	Column1 pgtype.Interval
	Limit   int32
}

func (q *Queries) DeleteOldOrdersBatch(ctx context.Context, arg DeleteOldOrdersBatchParams) error {
	_, err := q.db.Exec(ctx, deleteOldOrdersBatch, arg.Column1, arg.Limit)
	return err
}

const deleteProcessedOutboxBatch = `-- name: DeleteProcessedOutboxBatch :exec
DELETE FROM outbox
WHERE id IN (
    SELECT id
    FROM outbox
    WHERE processed_at IS NOT NULL
    AND processed_at < now() - $1::interval
    LIMIT $2
)
`

type DeleteProcessedOutboxBatchParams struct {
	Column1 pgtype.Interval
	Limit   int32
}

func (q *Queries) DeleteProcessedOutboxBatch(ctx context.Context, arg DeleteProcessedOutboxBatchParams) error {
	_, err := q.db.Exec(ctx, deleteProcessedOutboxBatch, arg.Column1, arg.Limit)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (
    aggregate_type,
    aggregate_id,
    event_type,
    payload
)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEventParams struct {
	AggregateType string
	AggregateID   int64
	EventType     string
	Payload       []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
