// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: e2e.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEvents = `-- name: DeleteEvents :exec
DELETE FROM e2e_events
WHERE sent_at < now() - interval '1 hour'
`

func (q *Queries) DeleteEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEvents)
	return err
}

const insertEventsBatch = `-- name: InsertEventsBatch :exec
INSERT INTO e2e_events(order_id, sent_at)
SELECT unnest($1::uuid[]), now()
`

func (q *Queries) InsertEventsBatch(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertEventsBatch, dollar_1)
	return err
}

const updateEventsBatch = `-- name: UpdateEventsBatch :exec
UPDATE e2e_events
SET received_at = now()
WHERE order_id = ANY($1::uuid[])
`

func (q *Queries) UpdateEventsBatch(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateEventsBatch, dollar_1)
	return err
}
