// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type E2eEvent struct {
	OrderID    pgtype.UUID
	SentAt     pgtype.Timestamp
	ReceivedAt pgtype.Timestamp
}
