apiVersion: skaffold/v2beta26  # подходящая для 2.17.2 версия
kind: Config
metadata:
  name: my-service
build:
  local:
    push: true
    useBuildkit: true
  artifacts:
    - image: 192.168.122.10:32000/checkout-service
      context: .
    - image: 192.168.122.10:32000/outbox-service
      context: ../outbox-service
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
      - k8s/configmap.yaml
      - k8s/service-monitor.yaml
      - k8s/secret.yaml