// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPending = `-- name: CountPending :one
SELECT count(*) FROM outbox WHERE processed_at IS NULL
`

func (q *Queries) CountPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOutbox = `-- name: GetOutbox :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, created_at
FROM outbox
WHERE processed_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetOutboxRow struct {
	ID            int64
	AggregateType string
	AggregateID   int64
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamp
}

func (q *Queries) GetOutbox(ctx context.Context, limit int32) ([]GetOutboxRow, error) {
	rows, err := q.db.Query(ctx, getOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboxRow
	for rows.Next() {
		var i GetOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutbox = `-- name: UpdateOutbox :exec
UPDATE outbox
SET processed_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) UpdateOutbox(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, updateOutbox, dollar_1)
	return err
}
